# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d1c7316b21e3ac243ab083378e2789280826dc17dfe4014d352282b82ea0c622807d40483930027a6a09545205e81a95a0906f025209f03a2a8fcf04203c5e

test:
  secret_key_base: 7157ea5b6ae46fb433d5784497a12ddd3d9bdab0d067325aab47f28b553a4eb6b3377342756013c0d5934e47de271a5a126bdf4b114ae59f9fac7bff1e80be04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
